# Generated by Django 4.2.1 on 2023-06-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tache',
            name='fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(choices=[('elever', 'Elever'), ('medium', 'Medium'), ('faible', 'Faible')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.BooleanField(max_length=50),
        ),
    ]
